Add '-strip' flag for convert to get rid of EXIF data.
Sometimes EXIF data can make noteshrink.py crash, with error:
ValueError: cannot reshape array of size 1 into shape (3)